# Generated by Django 2.2.6 on 2019-10-30 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image_name', models.CharField(max_length=255)),
                ('actual_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('IP', models.TextField()),
                ('URL', models.TextField()),
                ('RAM', models.IntegerField()),
                ('CPU', models.IntegerField()),
                ('cpu_remaining', models.IntegerField(default=models.IntegerField())),
                ('memory_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slave_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('IP', models.TextField()),
                ('URL', models.TextField()),
                ('RAM', models.IntegerField(null=True)),
                ('CPU', models.IntegerField(null=True)),
                ('ports', models.TextField()),
                ('ssh_port', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('CR', 'Created'), ('RU', 'Running'), ('SP', 'Stopped')], default='CR', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
