# Generated by Django 2.1.3 on 2019-10-23 20:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('actual_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('IPs', models.GenericIPAddressField()),
                ('RAM', models.IntegerField()),
                ('CPU_usage', models.IntegerField()),
                ('ports', models.IntegerField(validators=[django.core.validators.int_list_validator])),
                ('status', models.CharField(choices=[('ID', 'Idle'), ('ST', 'Started'), ('RU', 'Running'), ('SP', 'Stopped')], default='ID', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
