# Generated by Django 2.1.3 on 2019-10-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191028_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='ports',
            field=models.IntegerField(),
        ),
    ]
