# Generated by Django 2.1.3 on 2019-10-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191028_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='CPU_usage',
            new_name='CPU',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
