# Generated by Django 2.2.6 on 2019-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_slave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('IP', models.TextField()),
                ('URL', models.TextField()),
                ('RAM', models.IntegerField()),
                ('CPU', models.IntegerField()),
            ],
        ),
    ]
