# Generated by Django 2.2.6 on 2019-10-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_slave'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='slave_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='ssh_port',
            field=models.IntegerField(default=3231),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='ports',
            field=models.TextField(),
        ),
    ]
