# Generated by Django 2.2.6 on 2019-10-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191030_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('RU', 'Running'), ('SP', 'Stopped')], default='CR', max_length=2),
        ),
    ]
