# Generated by Django 2.2.6 on 2019-10-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191030_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='RAM',
        ),
    ]
