# Generated by Django 2.2.6 on 2019-10-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_instance_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='RAM',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
    ]
