# Generated by Django 2.2.6 on 2019-10-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_instance_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='CPU',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='RAM',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='slave_id',
            field=models.IntegerField(null=True),
        ),
    ]
