# Generated by Django 2.2.6 on 2019-10-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191030_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='ssh_port',
            field=models.IntegerField(null=True),
        ),
    ]
