# Generated by Django 2.2.6 on 2019-10-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191030_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
